### ISSUE TITLE
sempre que possível usar os #defines

### ISSUE THREAD

**Issue by rafaelcorsi** [LiuSeeker/aps1-embarcados#2]
https://github.com/LiuSeeker/aps1-embarcados/blob/77cf97db14b21b85916f0b51ac4bd77687b3c104/src/main.c#L246

**Comment by rafaelcorsi** [comment]
https://github.com/LiuSeeker/aps1-embarcados/blob/77cf97db14b21b85916f0b51ac4bd77687b3c104/src/main.c#L280

**Comment by vitorsv1** [comment]
Mesmo o PIOA e o PIOC ja esterem definidos no programa precisaria criar um define pra eles?

**Comment by rafaelcorsi** [comment]
imagina que você queria mudar o pino e ele vai para outro PIO, vai ter que varrer todo o seu código em busca do PIOA e trocar para o PIOx. Se você usasse o `#define BUZ_PIO PIOA` bastava trocar no #define para  `#define BUZ_PIO PIOx` e não precisa alterar o programa.

```c
 pio_set( BUZ_PIO, BUZ_PIO_IDX_MASK); 
```

**Comment by vitorsv1** [comment]
É verdade!!
